project:
  type: website
  output-dir: docs

website:
  title: "Csenge + Lapo"
  navbar:
    background: transparent
    left:
      - text: Home
        href: index.qmd
      - text: Location
        href: location.qmd
      - text: Info
        href: info.qmd
      - text: RSVP HU
        href: rsvp_hu.qmd
      - text: RSVP IT
        href: rsvp_it.qmd

from: markdown+emoji

format:
  html:
    theme: 
    - cosmo
    - color.scss



